version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mas_postgres
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: OzKeTn!6
      POSTGRES_DB: my-admin-station_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: mas_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  backend:
    build: .
    container_name: my-admin-station
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  db_data: